package cn.iocoder.yudao.module.mes.dal.dataobject.qms;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class QmsYieldAnalysisSourcePreviewRow extends QmsYieldAnalysisSourceRow {

    private String operationCode;
    private String operationName;
    private Long sourceAdhesiveReportId;
    private Long sourceAdhesive2ReportId;
    private Long sourcePressSlotReportId;
    private Long sourceSlittingSliceId;
    private String sourceSliceSerialNo;
    private String sourcePressSlotProductionBatchNo;
    private String sourceAdhesive2ProductionBatchNo;
    private String sourceStockBatchNo;
    private BigDecimal sourceLockQty;
    private BigDecimal sourceConsumeQty;
    private String sourceConsumeTxnNo;
    private LocalDateTime sourceConsumeTime;
    private String sourceBatchNo;
    private String sourceProductionBatchNo;
    private BigDecimal sourceLength;
    private String productionBatchNo;
    private String parentProductionBatchNo;
    private String sourceMenuCode;
    private String reportType;
    private String reportUom;
    private LocalDate reportDate;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private BigDecimal feedQty;
    private BigDecimal goodQty;
    private BigDecimal scrapQty;
    private BigDecimal inputLength;
    private BigDecimal startPosition;
    private BigDecimal endPosition;
    private BigDecimal lossLength;
    private BigDecimal outputLength;
    private BigDecimal napSampleLength;
    private String cutMode;
    private String sliceSerialNo;
    private Integer sliceIndex;
    private BigDecimal sliceLength;
    private String sizeCode;
    private String sizeName;
    private String printStatus;
    private Integer printCount;
    private LocalDateTime lastPrintTime;
    private String scanStatus;
    private LocalDateTime scanTime;
    private String scannerName;
    private String outputStockPostStatus;
    private LocalDateTime outputStockPostTime;
    private String pressureRollerMaterialCode;
    private String pressureRollerBatchNo;
    private String bearingMaterialCode;
    private String bearingBatchNo;
    private Integer rollerCleanAccumulatedPcs;
    private Integer bearingReplaceAccumulatedPcs;
    private String glueBoardModel;
    private String glueBoardMaterialCode;
    private String glueBoardBatchNo;
    private BigDecimal glueBoardStartPosition;
    private BigDecimal glueBoardUseLength;
    private String productQualityStatus;
    private String qualityLockReason;
    private String bladeMaterialCode;
    private String bladeBatchNo;
    private String feltMaterialCode;
    private String feltBatchNo;
    private Integer bladeUseCount;
    private Integer feltUseCount;
    private String qualityRiskFlag;
    private String qualityRiskSnapshotJson;
    private Long inspectionTaskId;
    private String inspectionTaskNo;
    private String inspectionStatus;
    private String inspectionResult;
    private String inspectorName;
    private LocalDateTime inspectionTime;
    private String inspectionRemark;
    private String recorderName;
    private LocalDateTime recorderTime;
    private String confirmerName;
    private LocalDateTime confirmerTime;
    private String remark;
}
