import { afterEach, describe, expect, it } from "vitest";
import { createServer, type Server } from "node:http";
import { mkdtemp, readFile, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { createEmptyDesign } from "@doormes/domain";
import { createRectangularWindowCommand, createResizeWindowCommand, DesignSession } from "@doormes/application";
import { DESIGN_REVIEW_ROLES, type FactoryCommand, type FactoryWorkspace } from "@doormes/contracts/factory-workflow";
import Ajv from "ajv";
import { FileFactoryStore } from "./store.js";
import { createFactoryHttpHandler } from "./http.js";

const paths: string[] = [], servers: Server[] = [], password = "Factory-test-password-2026!";
afterEach(async () => {
  for (const server of servers.splice(0)) await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve()));
  // Only exact mkdtemp-owned fixture directories are removed.
  for (const path of paths.splice(0)) await rm(path, { recursive: true, force: true });
});
async function fixture() {
  const path = await mkdtemp(join(tmpdir(), "doormes-factory-test-")); paths.push(path);
  const store = new FileFactoryStore(path, password), handler = createFactoryHttpHandler(store);
  const server = createServer((req, res) => { void handler(req, res); }); servers.push(server);
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address(); if (!address || typeof address === "string") throw new Error("No test address");
  const base = "http://127.0.0.1:" + address.port + "/api/factory";
  const login = async (username: string) => { const response = await fetch(base + "/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username, password }) }); expect(response.status).toBe(200); return response.headers.get("set-cookie")!.split(";")[0]!; };
  const request = (route: string, cookie = "", body?: unknown, origin?: string) => fetch(base + route, { method: body ? "POST" : "GET", headers: { cookie, ...(body ? { "content-type": "application/json" } : {}), ...(origin ? { origin } : {}) }, body: body ? JSON.stringify(body) : undefined });
  return { path, store, login, request };
}
describe("real HTTP + filesystem factory prototype", () => {
  it("persists shared cross-batch changes, rejects stale whole-group issue without writing and replays one atomic commit", async () => {
    const f = await fixture(), cookies = new Map<string, string>();
    let workspace = await f.store.read(), serial = 0;
    const send = async (role: string, command: FactoryCommand, expectedStatus = 200) => {
      if (!cookies.has(role)) cookies.set(role, await f.login(role));
      const body = { expectedRevision: workspace.revision, idempotencyKey: "scheme-http-" + ++serial, command };
      const before = await readFile(join(f.path, "workspace.json"), "utf8");
      const response = await f.request("/commands", cookies.get(role), body); expect(response.status).toBe(expectedStatus);
      const result = await response.json();
      if (expectedStatus === 200) workspace = result.workspace;
      else expect(await readFile(join(f.path, "workspace.json"), "utf8")).toBe(before);
      return { body, result };
    };
    const session = new DesignSession(createEmptyDesign("SCHEME-HTTP"));
    session.execute(createRectangularWindowCommand({ commandId: "CREATE", windowId: "W1", mark: "C1", widthMm: 1200, heightMm: 1500, profileSystemId: "AL70", defaultGlassTypeId: "GL-LOWE-24", defaultHardwareSetId: "HW-TT-STD" }));
    const initialDesignId = (await send("designer", { type: "save-design", name: "跨批样例", drawingNumber: "GROUP-HTTP", document: session.document })).result.targetId as string;
    const release = async (designId: string) => {
      await send("designer", { type: "submit-design", designId });
      for (const role of DESIGN_REVIEW_ROLES) await send(role, { type: "review-design", designId, role, decision: "approve", note: "共同图纸核对" });
      return (await send("designer", { type: "release-design", designId, productCode: "GROUP-HTTP" })).result.targetId as string;
    };
    const releaseId = await release(initialDesignId);
    const orderId = (await send("sales", { type: "create-order", number: "GROUP-HTTP-SO", customer: "客户", kind: "standard", quantity: 4, releaseId, requirement: { widthMm: 1200, heightMm: 1500, material: "AL70", glass: "GL-LOWE-24", hardware: "HW-TT-STD", finish: "内RAL9016 / 外RAL7016", dueDate: "", note: "" } })).result.targetId as string;
    await send("sales", { type: "confirm-order", orderId }); const lineId = workspace.orders[0]!.lines[0]!.id;
    const baseIds: string[] = [];
    for (const batch of ["A", "B"]) {
      const packageId = (await send("production", { type: "create-package", orderId, lineId, batch, quantity: 2 })).result.targetId as string; baseIds.push(packageId);
      for (const role of ["process", "procurement", "quality"] as const) await send(role, { type: "review-package", packageId, role, decision: "approve", note: "核对" });
      await send("production", { type: "issue-package", packageId }); await send("operator", { type: "acknowledge-package", packageId });
    }
    const create: Extract<FactoryCommand, { type: "create-change-scheme" }> = { type: "create-change-scheme", name: "两批统一尺寸修订", reason: "客户变更", procurement: "新料核对", cost: "差额确认", delivery: "交期确认", scopes: workspace.packages.map((packet) => ({ packageId: packet.id, batch: packet.batch, fromStep: "CUT", pieceNumbers: packet.pieceNumbers, disposition: "use-as-is" })) };
    await send("operator", create, 403);
    await send("sales", { ...create, scopes: [create.scopes[0]!] }, 400);
    await send("sales", { ...create, scopes: [create.scopes[0]!, create.scopes[0]!] }, 400);
    const oldRevision = workspace.revision, oldSnapshot = structuredClone(workspace);
    const created = await send("sales", create), schemeId = created.result.targetId as string;
    const createdBytes = await readFile(join(f.path, "workspace.json"), "utf8");
    const creationReplay = await f.request("/commands", cookies.get("sales"), created.body);
    expect(creationReplay.status).toBe(200); expect((await creationReplay.json()).replayed).toBe(true);
    expect(await readFile(join(f.path, "workspace.json"), "utf8")).toBe(createdBytes);
    const leaderId = workspace.changeSchemes![0]!.changeIds[0]!, design = workspace.designs.find((entry) => entry.id === workspace.changes[0]!.designId)!;
    const edit = new DesignSession(design.document);
    edit.execute(createResizeWindowCommand({ commandId: "RESIZE", windowId: "W1", widthMm: 1260, heightMm: 1500 }));
    await send("designer", { type: "save-design", designId: design.id, name: design.name, drawingNumber: design.drawingNumber, document: edit.document });
    const targetReleaseId = await release(design.id);
    await send("designer", { type: "submit-change-scheme", schemeId });
    await send("reviewer", { type: "review-change", changeId: leaderId, role: "reviewer", decision: "approve", note: "单独会签禁止" }, 422);
    await send("sales", { type: "review-change-scheme", schemeId, role: "reviewer", decision: "approve", note: "越权" }, 403);
    const approve = async () => { for (const role of DESIGN_REVIEW_ROLES) await send(role, { type: "review-change-scheme", schemeId, role, decision: "approve", note: "整组核对" }); };
    await approve();
    await send("production", { type: "issue-change", changeId: leaderId }, 422);
    await send("production", { type: "issue-change-scheme", schemeId }, 422); // no customer confirmation
    await send("sales", { type: "confirm-customer", orderId, lineId, releaseId: targetReleaseId });
    const staleRevision = workspace.revision;
    await send("operator", { type: "record-execution", packageId: baseIds[1]!, stepId: "MATERIAL", kind: "material", quantity: 2, pieceNumbers: workspace.packages[1]!.pieceNumbers, result: "pass", actual: "第二批新增实况" });
    const rejected = await send("production", { type: "issue-change-scheme", schemeId }, 409);
    expect(rejected.result.error.code).toBe("STALE_IMPACT");
    expect(rejected.result.error.message).toContain("批次 B");
    expect(workspace.packages).toHaveLength(2); expect(workspace.changes.every((entry) => entry.status === "approved")).toBe(true);
    expect((await f.request("/commands", cookies.get("production"), { expectedRevision: staleRevision, idempotencyKey: "scheme-stale-revision", command: { type: "issue-change-scheme", schemeId } })).status).toBe(409);
    await send("production", { type: "refresh-change-scheme-impact", schemeId }); await approve();
    const orderRevision = workspace.orders[0]!.revision;
    const issued = await send("production", { type: "issue-change-scheme", schemeId });
    expect(workspace.packages).toHaveLength(4);
    expect(workspace.packages.slice(2).every((entry) => entry.orderRevision === orderRevision + 1 && entry.releaseId === targetReleaseId)).toBe(true);
    const issuedBytes = await readFile(join(f.path, "workspace.json"), "utf8");
    const replay = await f.request("/commands", cookies.get("production"), issued.body);
    expect(replay.status).toBe(200); expect((await replay.json()).replayed).toBe(true);
    expect(await readFile(join(f.path, "workspace.json"), "utf8")).toBe(issuedBytes);
    await send("sales", { type: "withdraw-change-scheme", schemeId, note: "已下达禁止撤回" }, 403);
    await send("operator", { type: "acknowledge-change", changeId: leaderId });
    const restored = await new FileFactoryStore(f.path, password).read();
    expect(restored).toEqual(workspace); expect(restored.changeSchemes).toHaveLength(1);
    expect(await f.store.version(oldRevision)).toEqual(oldSnapshot);
    expect(await f.store.version(oldRevision + 1)).toMatchObject({ changeSchemes: [{ id: schemeId }], changes: [{ status: "designing" }, { status: "designing" }], packages: oldSnapshot.packages });
    const responseSchema = await (await f.request("/schema/workspace", cookies.get("sales"))).json();
    expect(new Ajv().compile(responseSchema)(JSON.parse(JSON.stringify(restored)))).toBe(true);
    const commandSchema = await (await f.request("/schema", cookies.get("sales"))).json(), validCommand = new Ajv().compile(commandSchema);
    expect(validCommand(created.body)).toBe(true); expect(validCommand(issued.body)).toBe(true);
    expect(validCommand({ ...created.body, command: { ...create, scopes: [{ ...create.scopes[0], extra: "禁止" }, create.scopes[1]] } })).toBe(false);
  }, 25000);
  it("archives quantity amendments and unissued cancellation, releases allocation and restores after restart", async () => {
    const f = await fixture(), cookies = new Map<string, string>();
    let workspace = await f.store.read(), serial = 0;
    const send = async (role: string, command: FactoryCommand, expectedStatus = 200) => {
      if (!cookies.has(role)) cookies.set(role, await f.login(role));
      const body = { expectedRevision: workspace.revision, idempotencyKey: "quantity-http-" + ++serial, command };
      const before = await readFile(join(f.path, "workspace.json"), "utf8");
      const response = await f.request("/commands", cookies.get(role), body); expect(response.status).toBe(expectedStatus);
      const result = await response.json();
      if (expectedStatus === 200) workspace = result.workspace;
      else expect(await readFile(join(f.path, "workspace.json"), "utf8")).toBe(before);
      return { body, result };
    };
    const session = new DesignSession(createEmptyDesign("QUANTITY-HTTP"));
    session.execute(createRectangularWindowCommand({ commandId: "CREATE", windowId: "W1", mark: "C1", widthMm: 1200, heightMm: 1500, profileSystemId: "AL70", defaultGlassTypeId: "GL-LOWE-24", defaultHardwareSetId: "HW-TT-STD" }));
    const designId = (await send("designer", { type: "save-design", name: "数量修订测试", drawingNumber: "HTTP-QTY", document: session.document })).result.targetId;
    await send("designer", { type: "submit-design", designId });
    for (const role of DESIGN_REVIEW_ROLES) await send(role, { type: "review-design", designId, role, decision: "approve", note: "核对" });
    const releaseId = (await send("designer", { type: "release-design", designId, productCode: "HTTP-QTY" })).result.targetId;
    const orderId = (await send("sales", { type: "create-order", number: "HTTP-QTY-SO", customer: "客户", kind: "standard", quantity: 3, releaseId, requirement: { widthMm: 1200, heightMm: 1500, material: "AL70", glass: "GL-LOWE-24", hardware: "HW-TT-STD", finish: "内RAL9016 / 外RAL7016", dueDate: "", note: "" } })).result.targetId;
    await send("sales", { type: "confirm-order", orderId }); const lineId = workspace.orders[0]!.lines[0]!.id;
    const packageId = (await send("production", { type: "create-package", orderId, lineId, batch: "OLD", quantity: 2 })).result.targetId;
    for (const role of ["process", "procurement", "quality"] as const) await send(role, { type: "review-package", packageId, role, decision: "approve", note: "核对" });
    const oldRevision = workspace.revision, oldPacket = structuredClone(workspace.packages[0]!);
    await send("operator", { type: "cancel-package", packageId, note: "越权" }, 403);
    await send("sales", { type: "revise-order-quantity", orderId, lineId, quantity: 1, note: "已分配不能减" }, 422);
    await send("sales", { type: "revise-order-quantity", orderId, lineId, quantity: 1.5, note: "不是整数" }, 400);
    const cancellation = await send("production", { type: "cancel-package", packageId, note: "未下达批次撤销" });
    const bytes = await readFile(join(f.path, "workspace.json"), "utf8");
    const replay = await f.request("/commands", cookies.get("production"), cancellation.body); expect(replay.status).toBe(200); expect((await replay.json()).replayed).toBe(true);
    expect(await readFile(join(f.path, "workspace.json"), "utf8")).toBe(bytes);
    const amendment = await send("sales", { type: "revise-order-quantity", orderId, lineId, quantity: 1, note: "客户确认减量" });
    const quantityBytes = await readFile(join(f.path, "workspace.json"), "utf8");
    const quantityReplay = await f.request("/commands", cookies.get("sales"), amendment.body); expect(quantityReplay.status).toBe(200); expect((await quantityReplay.json()).replayed).toBe(true);
    expect(await readFile(join(f.path, "workspace.json"), "utf8")).toBe(quantityBytes);
    await send("production", { type: "create-package", orderId, lineId, batch: "OLD" }, 422);
    const newId = (await send("production", { type: "create-package", orderId, lineId, batch: "NEW" })).result.targetId;
    for (const role of ["process", "procurement", "quality"] as const) await send(role, { type: "review-package", packageId: newId, role, decision: "approve", note: "核对" });
    await send("production", { type: "issue-package", packageId: newId });
    await send("production", { type: "cancel-package", packageId: newId, note: "已下达禁止直接撤销" }, 422);
    const restarted = new FileFactoryStore(f.path, password), recovered = await restarted.read();
    expect(recovered).toEqual(workspace);
    expect(recovered.orders[0]!.quantityRevisions).toHaveLength(1);
    expect(recovered.packages[0]).toMatchObject({ status: "cancelled", bom: oldPacket.bom, reviews: oldPacket.reviews, pieceNumbers: oldPacket.pieceNumbers });
    expect(recovered.packages[1]!.quantity).toBe(1);
    expect(recovered.packages[1]!.pieceNumbers.some((piece) => oldPacket.pieceNumbers.includes(piece))).toBe(false);
    const sales = await f.login("sales");
    const historyResponse = await f.request("/versions/" + oldRevision, sales); expect(historyResponse.status).toBe(200);
    const history = await historyResponse.json();
    // History endpoint returns the original workspace, not today's amended quantities.
    expect(history.workspace ?? history).toMatchObject({ orders: [{ lines: [{ quantity: 3 }] }], packages: [{ status: "approved" }] });
  }, 20000);
  it("validates active assignees server-side and restores R&D handovers and task ownership", async () => {
    const f = await fixture(), admin = await f.login("admin"), reviewer = await f.login("reviewer"), designer = await f.login("designer"), sales = await f.login("sales");
    expect((await f.request("/people")).status).toBe(401);
    const directory = await (await f.request("/people", designer)).json();
    expect(directory.people.some((person: { id: string }) => person.id === "user-designer")).toBe(true);
    expect(JSON.stringify(directory)).not.toContain("passwordHash");
    expect(JSON.stringify(directory)).not.toContain("username");
    const add = await f.request("/users", admin, { username: "designer-two", name: "第二设计", roles: ["designer"], enabled: true, password });
    expect(add.status).toBe(200);
    const secondId = (await add.json()).users.find((user: { username: string }) => user.username === "designer-two").id;
    const second = await f.login("designer-two");
    let workspace = await f.store.read(), serial = 0;
    const send = async (cookie: string, command: FactoryCommand, status = 200) => {
      const response = await f.request("/commands", cookie, { expectedRevision: workspace.revision, idempotencyKey: "task-http-" + ++serial, command });
      expect(response.status).toBe(status);
      if (status === 200) workspace = (await response.json()).workspace;
    };
    await send(sales, { type: "create-order", number: "TASK-HTTP", customer: "客户", kind: "custom", quantity: 1, requirement: { widthMm: 1200, heightMm: 1500, material: "AL70", glass: "GL-LOWE-24", hardware: "HW-TT-STD", finish: "内RAL9016 / 外RAL7016", dueDate: "2026-10-15", note: "任务领取与交接" } });
    const task = workspace.engineeringRequests[0]!, design = workspace.designs[0]!;
    await send(reviewer, { type: "assign-engineering", requestId: task.id, assigneeId: "not-a-real-user", note: "不存在" }, 422);
    await send(reviewer, { type: "assign-engineering", requestId: task.id, assigneeId: secondId, note: "分派第二设计" });
    await send(designer, { type: "claim-engineering", requestId: task.id }, 403);
    await send(second, { type: "claim-engineering", requestId: task.id });
    await send(designer, { type: "save-design", designId: design.id, name: "非法覆盖", drawingNumber: design.drawingNumber, document: design.document }, 403);
    await send(second, { type: "save-design", designId: design.id, name: "本人任务", drawingNumber: design.drawingNumber, document: design.document });
    expect((await f.request("/users", admin, { id: secondId, username: "designer-two", name: "第二设计", roles: ["designer"], enabled: false })).status).toBe(200);
    await send(reviewer, { type: "assign-engineering", requestId: task.id, assigneeId: secondId, note: "停用不能分派" }, 422);
    await send(reviewer, { type: "assign-engineering", requestId: task.id, assigneeId: "user-designer", note: "交接第一设计" });
    await send(designer, { type: "claim-engineering", requestId: task.id });
    const restarted = await new FileFactoryStore(f.path, password).read();
    expect(restarted.engineeringRequests[0]).toMatchObject({ assigneeId: "user-designer", assignedBy: "user-reviewer", status: "designing" });
    expect(restarted.engineeringRequests[0]!.claimedAt).toBeTruthy();
    expect(restarted.designs[0]!.name).toBe("本人任务");
    expect(restarted.audit.filter((entry) => entry.targetId === task.id).map((entry) => entry.action)).toEqual(["assign-engineering", "claim-engineering", "assign-engineering", "claim-engineering"]);
  }, 20000);
  it("persists scoped first-work through authenticated order, design, review and execution endpoints", async () => {
    const f = await fixture();
    const cookies = new Map<string, string>();
    let state = (await f.request("/workspace", await f.login("designer"))).status;
    expect(state).toBe(200);
    let workspace = await f.store.read(), serial = 0;
    const send = async (role: string, command: FactoryCommand, expectedStatus = 200) => {
      if (!cookies.has(role)) cookies.set(role, await f.login(role));
      const response = await f.request("/commands", cookies.get(role), { expectedRevision: workspace.revision, idempotencyKey: "scope-http-" + ++serial, command });
      expect(response.status).toBe(expectedStatus);
      const result = await response.json();
      if (response.status === 200) workspace = result.workspace as FactoryWorkspace;
      return result.targetId as string;
    };
    const session = new DesignSession(createEmptyDesign("SCOPE-HTTP"));
    session.execute(createRectangularWindowCommand({ commandId: "CREATE", windowId: "W1", mark: "C1", widthMm: 1200, heightMm: 1500, profileSystemId: "AL70", defaultGlassTypeId: "GL-LOWE-24", defaultHardwareSetId: "HW-TT-STD" }));
    const designId = await send("designer", { type: "save-design", name: "接口标准窗", drawingNumber: "HTTP-SCOPE-01", document: session.document });
    await send("designer", { type: "submit-design", designId });
    for (const role of DESIGN_REVIEW_ROLES) await send(role, { type: "review-design", designId, role, decision: "approve", note: "接口逐岗核对" });
    const releaseId = await send("designer", { type: "release-design", designId, productCode: "HTTP-STANDARD" });
    const orderId = await send("sales", { type: "create-order", number: "HTTP-SO-1", customer: "测试客户", kind: "standard", quantity: 3, releaseId, requirement: { widthMm: 1200, heightMm: 1500, material: "AL70", glass: "GL-LOWE-24", hardware: "HW-TT-STD", finish: "内RAL9016 / 外RAL7016", dueDate: "", note: "" } });
    await send("sales", { type: "confirm-order", orderId });
    const lineId = workspace.orders[0]!.lines[0]!.id;
    await send("production", { type: "create-package", orderId, lineId, batch: "HTTP-B1", quantity: 0.5 }, 400);
    const packageId = await send("production", { type: "create-package", orderId, lineId, batch: "HTTP-B1", quantity: 2 });
    await send("production", { type: "create-package", orderId, lineId, batch: "HTTP-B2", quantity: 2 }, 422);
    await send("production", { type: "create-package", orderId, lineId, batch: "HTTP-B2" });
    await send("production", { type: "create-package", orderId, lineId, batch: "HTTP-B3" }, 422);
    expect(workspace.packages.map((entry) => entry.quantity)).toEqual([2, 1]);
    for (const role of ["process", "procurement", "quality"] as const) await send(role, { type: "review-package", packageId, role, decision: "approve", note: "制造包通过" });
    await send("production", { type: "issue-package", packageId });
    await send("operator", { type: "acknowledge-package", packageId });
    const packet = workspace.packages[0]!, pieceNumbers = [packet.pieceNumbers[0]!];
    const application = { type: "create-deviation" as const, packageId, reason: "先行领料", actual: "待补图", pieceNumbers, stepIds: ["MATERIAL"], risk: "用料待确认", control: "隔离核对" };
    await send("sales", application, 403);
    await send("operator", { ...application, pieceNumbers: ["FOREIGN-PIECE"] }, 422);
    const { risk: _risk, ...missingRisk } = application;
    const malformed = await f.request("/commands", cookies.get("operator"), { expectedRevision: workspace.revision, idempotencyKey: "scope-malformed", command: missingRisk });
    expect(malformed.status).toBe(400);
    const id = await send("operator", application);
    for (const role of ["production", "quality"] as const) await send(role, { type: "review-deviation", deviationId: id, role, decision: "approve", note: "仅此件与领料工序" });
    const execution = { type: "record-execution" as const, packageId, stepId: "MATERIAL", kind: "material" as const, quantity: 1, pieceNumbers, result: "recorded" as const, actual: "真实领料" };
    await send("operator", execution, 422);
    await send("operator", { ...execution, deviationId: id, pieceNumbers: [packet.pieceNumbers[1]!] }, 422);
    const executionId = await send("operator", { ...execution, deviationId: id });
    const restart = new FileFactoryStore(f.path, password), restored = await restart.read();
    expect(restored.deviations[0]).toMatchObject({ id, status: "authorized", scope: { pieceNumbers, stepIds: ["MATERIAL"], risk: "用料待确认", control: "隔离核对" }, executionIds: [executionId] });
    expect(restored.executions[0]).toMatchObject({ id: executionId, deviationId: id, pieceNumbers, stepId: "MATERIAL" });
    expect((await restart.version(workspace.revision - 1)).executions).toHaveLength(0);
    expect(restored.audit.at(-1)!.actorId).toBe("user-operator");
    const changeId = await send("sales", { type: "create-change", packageId, reason: "接口逐件沿用处置", batch: "HTTP-CHANGED", fromStep: "CUT", pieceNumbers: packet.pieceNumbers, disposition: "use-as-is", procurement: "无需补料", cost: "复核", delivery: "无" });
    const changeDesign = workspace.designs.find((entry) => entry.changeId === changeId)!;
    const edited = new DesignSession(changeDesign.document);
    edited.execute(createResizeWindowCommand({ commandId: "HTTP-RESIZE", windowId: "W1", widthMm: 1250, heightMm: 1500 }));
    await send("designer", { type: "save-design", designId: changeDesign.id, name: "变更图纸", drawingNumber: changeDesign.drawingNumber, document: edited.document });
    await send("designer", { type: "submit-design", designId: changeDesign.id });
    for (const role of DESIGN_REVIEW_ROLES) await send(role, { type: "review-design", designId: changeDesign.id, role, decision: "approve", note: "接口变更图核对" });
    const nextRelease = await send("designer", { type: "release-design", designId: changeDesign.id, productCode: "HTTP-STANDARD" });
    await send("designer", { type: "submit-change", changeId });
    for (const role of DESIGN_REVIEW_ROLES) await send(role, { type: "review-change", changeId, role, decision: "approve", note: "接口影响核对" });
    await send("sales", { type: "confirm-customer", orderId, lineId, releaseId: nextRelease });
    await send("production", { type: "issue-change", changeId }); await send("operator", { type: "acknowledge-change", changeId });
    const changed = workspace.packages.at(-1)!;
    for (const step of changed.route) await send(step.id === "QUALITY" ? "quality" : "operator", { type: "record-execution", packageId: changed.id, stepId: step.id, kind: step.id === "MATERIAL" ? "material" : step.id === "QUALITY" ? "inspection" : "process", quantity: changed.quantity, pieceNumbers: changed.pieceNumbers, result: "pass", actual: "新图逐件执行与终检" });
    const evidence = { type: "record-change-disposition" as const, changeId, pieceNumbers: packet.pieceNumbers, disposition: "use-as-is" as const, executionIds: [], replacementPairs: [], note: "原件逐件复核沿用，移交新版本制造包" };
    await send("sales", evidence, 403);
    await send("operator", { ...evidence, pieceNumbers: ["OTHER-BATCH-PIECE"] }, 422);
    const recordId = await send("operator", evidence);
    await send("quality", { type: "close-change", changeId, note: "只有记录未确认" }, 422);
    await send("production", { type: "review-change-disposition", changeId, recordId, role: "production", decision: "approve", note: "生产核对" });
    await send("quality", { type: "review-change-disposition", changeId, recordId, role: "quality", decision: "approve", note: "质量核对" });
    await send("quality", { type: "close-change", changeId, note: "逐件处置及新版本终检闭环" });
    const evidenceRestore = await new FileFactoryStore(f.path, password).read();
    expect(evidenceRestore.packages.map((entry) => entry.quantity)).toEqual([2, 1, 2]);
    expect(evidenceRestore.changes[0]).toMatchObject({ status: "closed", dispositionRecords: [{ id: recordId, pieceNumbers: packet.pieceNumbers, disposition: "use-as-is", actorId: "user-operator", reviews: [{ role: "production" }, { role: "quality" }] }] });
    expect(evidenceRestore.executions[0]).toEqual(restored.executions[0]);
    expect((await new FileFactoryStore(f.path, password).version(restored.revision)).changes).toEqual([]);
    expect(evidenceRestore.orders[0]!.lines[0]).toMatchObject({ releaseId, customerConfirmedReleaseId: releaseId });
    expect(evidenceRestore.releases.find((entry) => entry.id === nextRelease)!.scope).toEqual({ kind: "order-line", orderId, lineId });
    await send("sales", { type: "create-order", number: "CANNOT-REUSE-ORDER-CHANGE", customer: "客户", kind: "standard", quantity: 1, releaseId: nextRelease, requirement: { widthMm: 1250, heightMm: 1500, material: "AL70", glass: "GL-LOWE-24", hardware: "HW-TT-STD", finish: "内RAL9016 / 外RAL7016", dueDate: "", note: "" } }, 422);
    const otherBatch = workspace.packages[1]!;
    for (const role of ["process", "procurement", "quality"] as const) await send(role, { type: "review-package", packageId: otherBatch.id, role, decision: "approve", note: "另一批原图核对" });
    await send("production", { type: "issue-package", packageId: otherBatch.id }); await send("operator", { type: "acknowledge-package", packageId: otherBatch.id });
    const secondChange = await send("sales", { type: "create-change", packageId: otherBatch.id, reason: "另一批独立方案", batch: "OTHER-REV", fromStep: "CUT", pieceNumbers: otherBatch.pieceNumbers, disposition: "use-as-is", procurement: "核对", cost: "核对", delivery: "核对" });
    const secondDesign = workspace.designs.find((entry) => entry.changeId === secondChange)!;
    const secondEdit = new DesignSession(secondDesign.document);
    secondEdit.execute(createResizeWindowCommand({ commandId: "SECOND-RESIZE", windowId: "W1", widthMm: 1300, heightMm: 1500 }));
    await send("designer", { type: "save-design", designId: secondDesign.id, drawingNumber: secondDesign.drawingNumber, name: "另一批独立变更图", document: secondEdit.document });
    await send("designer", { type: "submit-design", designId: secondDesign.id });
    for (const role of DESIGN_REVIEW_ROLES) await send(role, { type: "review-design", designId: secondDesign.id, role, decision: "approve", note: "另一批图纸会签" });
    const secondRelease = await send("designer", { type: "release-design", designId: secondDesign.id, productCode: "HTTP-STANDARD" });
    await send("designer", { type: "submit-change", changeId: secondChange });
    for (const role of DESIGN_REVIEW_ROLES) await send(role, { type: "review-change", changeId: secondChange, role, decision: "approve", note: "另一批影响确认" });
    await send("sales", { type: "confirm-customer", orderId, lineId, releaseId: secondRelease });
    await send("designer", { type: "withdraw-change", changeId: secondChange, note: "非发起人" }, 403);
    await send("sales", { type: "withdraw-change", changeId: secondChange, note: "客户取消此批方案，保留原会签" });
    await send("production", { type: "issue-change", changeId: secondChange }, 422);
    const withdrawalRestore = await new FileFactoryStore(f.path, password).read();
    expect(withdrawalRestore.packages).toHaveLength(3); // Withdrawal never generated a replacement package.
    expect(withdrawalRestore.changes[0]!.customerConfirmation!.releaseId).toBe(nextRelease);
    expect(withdrawalRestore.changes[1]).toMatchObject({ status: "cancelled", customerConfirmation: { releaseId: secondRelease }, cancellation: { note: "客户取消此批方案，保留原会签", actorId: "user-sales" } });
    expect(withdrawalRestore.changes[1]!.reviews).toHaveLength(5);
    expect(withdrawalRestore.releases.find((entry) => entry.id === secondRelease)!.scope).toEqual({ kind: "order-line", orderId, lineId });
    expect(withdrawalRestore.orders[0]!.lines[0]!.releaseId).toBe(releaseId);
    // V3 belongs to another order branch from V1, not to its numeric predecessor V2.
    const branchComparison = await (await f.request("/releases/" + secondRelease + "/diff", cookies.get("designer"))).json();
    expect(branchComparison.before.id).toBe(releaseId); expect(branchComparison.after.id).toBe(secondRelease);
    expect(branchComparison.differences.some((entry: { category: string }) => entry.category === "geometry")).toBe(true);
    const chosen = await (await f.request("/releases/" + secondRelease + "/diff?against=" + nextRelease, cookies.get("designer"))).json();
    expect(chosen.before.id).toBe(nextRelease); expect(chosen.after.id).toBe(secondRelease);
    expect(chosen.differences.some((entry: { category: string }) => entry.category === "bom")).toBe(true);
    const reverse = await (await f.request("/releases/" + nextRelease + "/diff?against=" + secondRelease, cookies.get("quality"))).json();
    expect(reverse.before.id).toBe(secondRelease); expect(reverse.after.id).toBe(nextRelease);
    expect(reverse.differences).toEqual(chosen.differences.map((entry: { path: string; before: unknown; after: unknown; category: string }) => ({ ...entry, before: entry.after, after: entry.before })));
    expect((await (await f.request("/releases/" + releaseId + "/diff", cookies.get("designer"))).json()).before).toBeUndefined();
    expect((await (await f.request("/releases/" + releaseId + "/diff?against=" + releaseId, cookies.get("designer"))).json()).differences).toEqual([]);
    expect((await f.request("/releases/" + releaseId + "/diff?against=MISSING", cookies.get("designer"))).status).toBe(404);
    expect((await f.request("/releases/MISSING/diff", cookies.get("designer"))).status).toBe(404);
    expect((await f.request("/releases/" + releaseId + "/diff")).status).toBe(401);
    expect((await f.request("/versions")).status).toBe(401);
    const archived = await (await f.request("/versions/" + restored.revision, cookies.get("quality"))).json();
    expect(archived).toEqual(restored);
    expect((await (await f.request("/versions", cookies.get("quality"))).json()).revisions).toContain(restored.revision);
    expect(await f.store.read()).toEqual(withdrawalRestore);
    // Different products must not be accidentally compared as revisions of one design.
    const otherDesign = await send("designer", { type: "save-design", name: "另产品", drawingNumber: "HTTP-OTHER", document: session.document });
    await send("designer", { type: "submit-design", designId: otherDesign });
    for (const role of DESIGN_REVIEW_ROLES) await send(role, { type: "review-design", designId: otherDesign, role, decision: "approve", note: "另产品核对" });
    const otherRelease = await send("designer", { type: "release-design", designId: otherDesign, productCode: "OTHER-PRODUCT" });
    const headBytes = await readFile(join(f.path, "workspace.json"), "utf8");
    const unrelated = await f.request("/releases/" + releaseId + "/diff?against=" + otherRelease, cookies.get("designer"));
    expect(unrelated.status).toBe(422);
    expect((await unrelated.json()).error.code).toBe("INVALID_COMPARISON");
    expect(await readFile(join(f.path, "workspace.json"), "utf8")).toBe(headBytes);
  }, 20000);
  it("authenticates, enforces backend roles, optimistic revisions and exactly-once retries, then reloads files", async () => {
    const f = await fixture();
    expect((await f.request("/workspace")).status).toBe(401);
    const designer = await f.login("designer"), sales = await f.login("sales");
    const command = { type: "save-design", name: "HTTP草稿", drawingNumber: "HTTP-01", document: createEmptyDesign("HTTP-TEST") };
    const payload = { expectedRevision: 0, idempotencyKey: "request-1", command };
    expect((await f.request("/schema")).status).toBe(200);
    const workspaceSchema = await (await f.request("/schema/workspace")).json();
    expect(workspaceSchema.$id).toBe("urn:doormes:factory-workspace:v1");
    const validateWorkspace = new Ajv().compile(workspaceSchema);
    expect((await f.request("/commands", designer, { ...payload, actor: { roles: ["admin"] } })).status).toBe(400);
    expect((await f.request("/commands", designer, { ...payload, command: { ...command, document: null } })).status).toBe(400);
    expect((await f.request("/commands", sales, payload)).status).toBe(403);
    expect((await f.request("/commands", designer, payload, "https://untrusted.example")).status).toBe(403);
    const saved = await (await f.request("/commands", designer, payload)).json();
    expect(saved.workspace.revision).toBe(1);
    expect(validateWorkspace(saved.workspace)).toBe(true);
    const retry = await (await f.request("/commands", designer, payload)).json();
    expect(retry.replayed).toBe(true); expect(retry.targetId).toBe(saved.targetId);
    expect((await f.request("/commands", designer, { ...payload, idempotencyKey: "stale" })).status).toBe(409);
    expect((await f.request("/commands", designer, { ...payload, command: { ...command, name: "different" } })).status).toBe(409);
    const file = JSON.parse(await readFile(join(f.path, "workspace.json"), "utf8"));
    expect(file.workspace.designs[0].id).toBe(saved.targetId);
    const restart = new FileFactoryStore(f.path, "ignored-existing-password");
    expect((await restart.read()).designs[0]!.id).toBe(saved.targetId);
    expect((await restart.version(0)).designs).toEqual([]);
    expect(await restart.versions()).toEqual([1, 0]);
    const logout = await f.request("/logout", designer, {});
    expect(logout.status).toBe(200); expect((await f.request("/workspace", designer)).status).toBe(401);
  }, 20000);
  it("preserves the last administrator after rejected edits and revokes changed accounts", async () => {
    const f = await fixture(), admin = await f.login("admin");
    const failed = await f.request("/users", admin, { id: "user-admin", username: "admin", name: "管理员", roles: ["admin"], enabled: false });
    expect(failed.status).toBe(422);
    expect((await f.request("/users", admin)).status).toBe(200);
    const designer = await f.login("designer");
    expect((await f.request("/users", designer)).status).toBe(403);
    expect((await f.request("/users", admin, { id: "user-designer", username: "designer", name: "设计", roles: ["designer"], enabled: false })).status).toBe(200);
    expect((await f.request("/workspace", designer)).status).toBe(401);
    expect(await readFile(join(f.path, "users.json"), "utf8")).not.toContain(password);
  }, 20000);
  it("recovers a journal commit ahead of head and rejects corrupted snapshots without replacing them", async () => {
    const f = await fixture(), designer = await f.login("designer");
    const initial = await readFile(join(f.path, "workspace.json"), "utf8");
    await f.request("/commands", designer, { expectedRevision: 0, idempotencyKey: "recover", command: { type: "save-design", name: "recover", drawingNumber: "RECOVER", document: createEmptyDesign("RECOVER") } });
    await writeFile(join(f.path, "workspace.json"), initial);
    const recovered = new FileFactoryStore(f.path, password); expect((await recovered.read()).revision).toBe(1);
    const invalid = JSON.parse(await readFile(join(f.path, "workspace.json"), "utf8")); invalid.workspace.revision = 999;
    await writeFile(join(f.path, "workspace.json"), JSON.stringify(invalid));
    const corrupt = new FileFactoryStore(f.path, password);
    await expect(corrupt.read()).rejects.toThrow("校验失败");
    expect(JSON.parse(await readFile(join(f.path, "workspace.json"), "utf8")).workspace.revision).toBe(999);
  }, 20000);
});
